### ISSUE TITLE
Video Recording Does not Work Outside Visual Studio

### ISSUE THREAD

**Issue by levisiebens** [MathewSachin/Screna#10]
I have a WPF app where I've gotten the Screna recording API to grab video for me and output it to the x264 format. However, when I run this app from explorer (instead of the command line) the video file is created but no recording actually occurs. As far as I can tell no exception is being thrown so I'm at a loss as to why I don't get a video recording when I run the code outside of the Visual Studio environment.

Here's my creation code:

_provider = new ImageProviderHelper().GetImageProvider();
_videoWriter = new AviWriter(videoUploadName, AviCodec.X264);
_recorder = new Recorder(_videoWriter, _provider, 10);
_recorder.Start();

public IImageProvider GetImageProvider()
        {
            return new WindowProvider(() => Window.DesktopWindow,
                            Color.Empty,
                            new MouseCursor(),
                            new MouseKeyHook(VSR.Default.MouseClicks, VSR.Default.KeyStrokes));
        }

Steps:
1. Start WPF app from explorer (double click).
2. Trigger Start of recording.

Actual Result:
Video file is created, but always remains at 0k.

**Comment by levisiebens** [comment]
Quick update, I believe I've root caused the area in my code that was causing the problem. I tried using a basic console app an WPF app (both of which worked fine) however in my application I'm setting a proxy on the machine which is making the record.Start() call function incorrectly. If I run the proxy code on a separate thread everything seems to work okay (which is more then odd). If anyone is interested in the code causing the issue I can dig in deeper as needed. Thanks!

**Comment by MathewSachin** [comment]
This issue seems to be related to your particular use case. I think we don't need to modify Screna for this.
