### ISSUE TITLE
Is there a help topic of command line parameters for using captura.exe

### ISSUE THREAD

**Issue by PavelValentov** [MathewSachin/Screna#18]
As far as I understand captura.exe is a command line application.
What is parameters to launch a video capture in the command line?

**Comment by MathewSachin** [comment]
Please see https://github.com/MathewSachin/Captura/wiki/Command-line

**Comment by PavelValentov** [comment]
Sorry for the question.
I didn't find it before.

**Comment by MathewSachin** [comment]
No Problem 👍
