### ISSUE TITLE
Recorded video is black

### ISSUE THREAD

**Issue by GH-Richard** [MathewSachin/Screna#8]
When I use the example code within your learn.md, I get an .avi file, but the video is just a black window. Same results when i try to make a gif. When I add the cursor as overlay, I can see the cursor, but the rest is still black. Any idea why?

**Comment by MathewSachin** [comment]
Try passing IntPtr WindowProvider.DesktopHandle to the WindowProvider constructor and let me know the result

**Comment by GH-Richard** [comment]
Ok, its working now. Thank you very much!

**Comment by MathewSachin** [comment]
Ok. Would fix that into the project. Thank you for helping to improve Screna
